apiVersion: v1
kind: Pod 
metadata: 
  name: annotations
  annotations:
    description: "This is a backend service for handling expenses."
    git-commit: "abcd1234"
    documentation: "https://docs.example.com/service"
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80