apiVersion: v1
kind: Pod 
metadata: 
  name: pod-with-labels
  labels:
    project: expense
    module: backend
    environment: dev
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80