apiVersion: v1 
kind: Pod 
metadata: 
  name: pod-with-varfrom-configmap
spec:
  containers:
  - name: nginx
    image: nginx 
    envFrom:
    - configMapKeyRef:
        name: pod-config-map
    # env: 
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: pod-config-map
    #       key: course
    # - name: trainer
    #   valueFrom: 
    #     configMapKeyRef:
    #       name: pod-config-map
    #       key: trainer
    # - name: Duration 
    #   valueFrom:
    #     configMapKeyRef:
    #       name: pod-config-map
    #       key: duration 
 
