apiVersion: v1
kind: Pod 
metadata: 
 name: pod-secrets 
spec: 
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretKeyRef: 
      name: pod-secret 