apiVersion: v1 
kind: Pod 
metadata: 
  name: pod-with-Resources 
spec: 
  containers: 
  - name: nginx 
    image: nginx 
    resources:
      requests:
        cpu: 100m
        memory: 68mi 
      limits:
        cpu: 120m 
        memory: 100mi